spring:
  datasource:
    password: springstudent
    username: springstudent
    url: jdbc:mysql://localhost:3306/online_store_db?createDatabaseIfNotExist=true&UseSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
